package cm.cn.po;

public class JsCasequestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.real_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer realId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.content
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.an_A
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String anA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.an_B
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String anB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.an_C
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String anC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.an_D
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String anD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.an_E
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String anE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.answer
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveSix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_casequestion.case_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer caseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.id
     *
     * @return the value of js_casequestion.id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.id
     *
     * @param id the value for js_casequestion.id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.real_id
     *
     * @return the value of js_casequestion.real_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getRealId() {
        return realId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.real_id
     *
     * @param realId the value for js_casequestion.real_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setRealId(Integer realId) {
        this.realId = realId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.content
     *
     * @return the value of js_casequestion.content
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.content
     *
     * @param content the value for js_casequestion.content
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.an_A
     *
     * @return the value of js_casequestion.an_A
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnA() {
        return anA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.an_A
     *
     * @param anA the value for js_casequestion.an_A
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnA(String anA) {
        this.anA = anA == null ? null : anA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.an_B
     *
     * @return the value of js_casequestion.an_B
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnB() {
        return anB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.an_B
     *
     * @param anB the value for js_casequestion.an_B
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnB(String anB) {
        this.anB = anB == null ? null : anB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.an_C
     *
     * @return the value of js_casequestion.an_C
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnC() {
        return anC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.an_C
     *
     * @param anC the value for js_casequestion.an_C
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnC(String anC) {
        this.anC = anC == null ? null : anC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.an_D
     *
     * @return the value of js_casequestion.an_D
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnD() {
        return anD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.an_D
     *
     * @param anD the value for js_casequestion.an_D
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnD(String anD) {
        this.anD = anD == null ? null : anD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.an_E
     *
     * @return the value of js_casequestion.an_E
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnE() {
        return anE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.an_E
     *
     * @param anE the value for js_casequestion.an_E
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnE(String anE) {
        this.anE = anE == null ? null : anE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.answer
     *
     * @return the value of js_casequestion.answer
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.answer
     *
     * @param answer the value for js_casequestion.answer
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.reserve_one
     *
     * @return the value of js_casequestion.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.reserve_one
     *
     * @param reserveOne the value for js_casequestion.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.reserve_two
     *
     * @return the value of js_casequestion.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.reserve_two
     *
     * @param reserveTwo the value for js_casequestion.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.reserve_three
     *
     * @return the value of js_casequestion.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.reserve_three
     *
     * @param reserveThree the value for js_casequestion.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.reserve_four
     *
     * @return the value of js_casequestion.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveFour() {
        return reserveFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.reserve_four
     *
     * @param reserveFour the value for js_casequestion.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveFour(String reserveFour) {
        this.reserveFour = reserveFour == null ? null : reserveFour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.reserve_five
     *
     * @return the value of js_casequestion.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveFive() {
        return reserveFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.reserve_five
     *
     * @param reserveFive the value for js_casequestion.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveFive(String reserveFive) {
        this.reserveFive = reserveFive == null ? null : reserveFive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.reserve_six
     *
     * @return the value of js_casequestion.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveSix() {
        return reserveSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.reserve_six
     *
     * @param reserveSix the value for js_casequestion.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveSix(String reserveSix) {
        this.reserveSix = reserveSix == null ? null : reserveSix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_casequestion.case_id
     *
     * @return the value of js_casequestion.case_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_casequestion.case_id
     *
     * @param caseId the value for js_casequestion.case_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }
}