package cm.cn.po;

public class JsCase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.id
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.case_id
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.content
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.select_array
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private String selectArray;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.answer
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private String reserveFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private String reserveFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    private String reserveSix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.id
     *
     * @return the value of js_case.id
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.id
     *
     * @param id the value for js_case.id
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.case_id
     *
     * @return the value of js_case.case_id
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.case_id
     *
     * @param caseId the value for js_case.case_id
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.content
     *
     * @return the value of js_case.content
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.content
     *
     * @param content the value for js_case.content
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.select_array
     *
     * @return the value of js_case.select_array
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public String getSelectArray() {
        return selectArray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.select_array
     *
     * @param selectArray the value for js_case.select_array
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setSelectArray(String selectArray) {
        this.selectArray = selectArray == null ? null : selectArray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.answer
     *
     * @return the value of js_case.answer
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.answer
     *
     * @param answer the value for js_case.answer
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.reserve_one
     *
     * @return the value of js_case.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.reserve_one
     *
     * @param reserveOne the value for js_case.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.reserve_two
     *
     * @return the value of js_case.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.reserve_two
     *
     * @param reserveTwo the value for js_case.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.reserve_three
     *
     * @return the value of js_case.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.reserve_three
     *
     * @param reserveThree the value for js_case.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.reserve_four
     *
     * @return the value of js_case.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public String getReserveFour() {
        return reserveFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.reserve_four
     *
     * @param reserveFour the value for js_case.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setReserveFour(String reserveFour) {
        this.reserveFour = reserveFour == null ? null : reserveFour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.reserve_five
     *
     * @return the value of js_case.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public String getReserveFive() {
        return reserveFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.reserve_five
     *
     * @param reserveFive the value for js_case.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setReserveFive(String reserveFive) {
        this.reserveFive = reserveFive == null ? null : reserveFive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case.reserve_six
     *
     * @return the value of js_case.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public String getReserveSix() {
        return reserveSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case.reserve_six
     *
     * @param reserveSix the value for js_case.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:27:41 CST 2017
     */
    public void setReserveSix(String reserveSix) {
        this.reserveSix = reserveSix == null ? null : reserveSix.trim();
    }
}