package cm.cn.po;

public class JsCaseCasequestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case_casequestion.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case_casequestion.case_id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case_casequestion.content
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case_casequestion.select_array
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String selectArray;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case_casequestion.answer
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case_casequestion.reserve_one
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_case_casequestion.reerve_two
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String reerveTwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case_casequestion.id
     *
     * @return the value of js_case_casequestion.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case_casequestion.id
     *
     * @param id the value for js_case_casequestion.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case_casequestion.case_id
     *
     * @return the value of js_case_casequestion.case_id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case_casequestion.case_id
     *
     * @param caseId the value for js_case_casequestion.case_id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case_casequestion.content
     *
     * @return the value of js_case_casequestion.content
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case_casequestion.content
     *
     * @param content the value for js_case_casequestion.content
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case_casequestion.select_array
     *
     * @return the value of js_case_casequestion.select_array
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getSelectArray() {
        return selectArray;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case_casequestion.select_array
     *
     * @param selectArray the value for js_case_casequestion.select_array
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setSelectArray(String selectArray) {
        this.selectArray = selectArray == null ? null : selectArray.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case_casequestion.answer
     *
     * @return the value of js_case_casequestion.answer
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case_casequestion.answer
     *
     * @param answer the value for js_case_casequestion.answer
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case_casequestion.reserve_one
     *
     * @return the value of js_case_casequestion.reserve_one
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case_casequestion.reserve_one
     *
     * @param reserveOne the value for js_case_casequestion.reserve_one
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_case_casequestion.reerve_two
     *
     * @return the value of js_case_casequestion.reerve_two
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getReerveTwo() {
        return reerveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_case_casequestion.reerve_two
     *
     * @param reerveTwo the value for js_case_casequestion.reerve_two
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setReerveTwo(String reerveTwo) {
        this.reerveTwo = reerveTwo == null ? null : reerveTwo.trim();
    }
}