package cm.cn.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class JsExampaperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public JsExampaperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andExamSubjectIsNull() {
            addCriterion("exam_subject is null");
            return (Criteria) this;
        }

        public Criteria andExamSubjectIsNotNull() {
            addCriterion("exam_subject is not null");
            return (Criteria) this;
        }

        public Criteria andExamSubjectEqualTo(Integer value) {
            addCriterion("exam_subject =", value, "examSubject");
            return (Criteria) this;
        }

        public Criteria andExamSubjectNotEqualTo(Integer value) {
            addCriterion("exam_subject <>", value, "examSubject");
            return (Criteria) this;
        }

        public Criteria andExamSubjectGreaterThan(Integer value) {
            addCriterion("exam_subject >", value, "examSubject");
            return (Criteria) this;
        }

        public Criteria andExamSubjectGreaterThanOrEqualTo(Integer value) {
            addCriterion("exam_subject >=", value, "examSubject");
            return (Criteria) this;
        }

        public Criteria andExamSubjectLessThan(Integer value) {
            addCriterion("exam_subject <", value, "examSubject");
            return (Criteria) this;
        }

        public Criteria andExamSubjectLessThanOrEqualTo(Integer value) {
            addCriterion("exam_subject <=", value, "examSubject");
            return (Criteria) this;
        }

        public Criteria andExamSubjectIn(List<Integer> values) {
            addCriterion("exam_subject in", values, "examSubject");
            return (Criteria) this;
        }

        public Criteria andExamSubjectNotIn(List<Integer> values) {
            addCriterion("exam_subject not in", values, "examSubject");
            return (Criteria) this;
        }

        public Criteria andExamSubjectBetween(Integer value1, Integer value2) {
            addCriterion("exam_subject between", value1, value2, "examSubject");
            return (Criteria) this;
        }

        public Criteria andExamSubjectNotBetween(Integer value1, Integer value2) {
            addCriterion("exam_subject not between", value1, value2, "examSubject");
            return (Criteria) this;
        }

        public Criteria andSelectOneIsNull() {
            addCriterion("select_one is null");
            return (Criteria) this;
        }

        public Criteria andSelectOneIsNotNull() {
            addCriterion("select_one is not null");
            return (Criteria) this;
        }

        public Criteria andSelectOneEqualTo(String value) {
            addCriterion("select_one =", value, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneNotEqualTo(String value) {
            addCriterion("select_one <>", value, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneGreaterThan(String value) {
            addCriterion("select_one >", value, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneGreaterThanOrEqualTo(String value) {
            addCriterion("select_one >=", value, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneLessThan(String value) {
            addCriterion("select_one <", value, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneLessThanOrEqualTo(String value) {
            addCriterion("select_one <=", value, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneLike(String value) {
            addCriterion("select_one like", value, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneNotLike(String value) {
            addCriterion("select_one not like", value, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneIn(List<String> values) {
            addCriterion("select_one in", values, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneNotIn(List<String> values) {
            addCriterion("select_one not in", values, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneBetween(String value1, String value2) {
            addCriterion("select_one between", value1, value2, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectOneNotBetween(String value1, String value2) {
            addCriterion("select_one not between", value1, value2, "selectOne");
            return (Criteria) this;
        }

        public Criteria andSelectMoreIsNull() {
            addCriterion("select_more is null");
            return (Criteria) this;
        }

        public Criteria andSelectMoreIsNotNull() {
            addCriterion("select_more is not null");
            return (Criteria) this;
        }

        public Criteria andSelectMoreEqualTo(String value) {
            addCriterion("select_more =", value, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreNotEqualTo(String value) {
            addCriterion("select_more <>", value, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreGreaterThan(String value) {
            addCriterion("select_more >", value, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreGreaterThanOrEqualTo(String value) {
            addCriterion("select_more >=", value, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreLessThan(String value) {
            addCriterion("select_more <", value, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreLessThanOrEqualTo(String value) {
            addCriterion("select_more <=", value, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreLike(String value) {
            addCriterion("select_more like", value, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreNotLike(String value) {
            addCriterion("select_more not like", value, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreIn(List<String> values) {
            addCriterion("select_more in", values, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreNotIn(List<String> values) {
            addCriterion("select_more not in", values, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreBetween(String value1, String value2) {
            addCriterion("select_more between", value1, value2, "selectMore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreNotBetween(String value1, String value2) {
            addCriterion("select_more not between", value1, value2, "selectMore");
            return (Criteria) this;
        }

        public Criteria andJudgeIsNull() {
            addCriterion("judge is null");
            return (Criteria) this;
        }

        public Criteria andJudgeIsNotNull() {
            addCriterion("judge is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeEqualTo(String value) {
            addCriterion("judge =", value, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeNotEqualTo(String value) {
            addCriterion("judge <>", value, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeGreaterThan(String value) {
            addCriterion("judge >", value, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeGreaterThanOrEqualTo(String value) {
            addCriterion("judge >=", value, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeLessThan(String value) {
            addCriterion("judge <", value, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeLessThanOrEqualTo(String value) {
            addCriterion("judge <=", value, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeLike(String value) {
            addCriterion("judge like", value, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeNotLike(String value) {
            addCriterion("judge not like", value, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeIn(List<String> values) {
            addCriterion("judge in", values, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeNotIn(List<String> values) {
            addCriterion("judge not in", values, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeBetween(String value1, String value2) {
            addCriterion("judge between", value1, value2, "judge");
            return (Criteria) this;
        }

        public Criteria andJudgeNotBetween(String value1, String value2) {
            addCriterion("judge not between", value1, value2, "judge");
            return (Criteria) this;
        }

        public Criteria andAnswerOneIsNull() {
            addCriterion("answer_one is null");
            return (Criteria) this;
        }

        public Criteria andAnswerOneIsNotNull() {
            addCriterion("answer_one is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerOneEqualTo(String value) {
            addCriterion("answer_one =", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneNotEqualTo(String value) {
            addCriterion("answer_one <>", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneGreaterThan(String value) {
            addCriterion("answer_one >", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneGreaterThanOrEqualTo(String value) {
            addCriterion("answer_one >=", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneLessThan(String value) {
            addCriterion("answer_one <", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneLessThanOrEqualTo(String value) {
            addCriterion("answer_one <=", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneLike(String value) {
            addCriterion("answer_one like", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneNotLike(String value) {
            addCriterion("answer_one not like", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneIn(List<String> values) {
            addCriterion("answer_one in", values, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneNotIn(List<String> values) {
            addCriterion("answer_one not in", values, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneBetween(String value1, String value2) {
            addCriterion("answer_one between", value1, value2, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneNotBetween(String value1, String value2) {
            addCriterion("answer_one not between", value1, value2, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreIsNull() {
            addCriterion("answer_more is null");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreIsNotNull() {
            addCriterion("answer_more is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreEqualTo(String value) {
            addCriterion("answer_more =", value, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreNotEqualTo(String value) {
            addCriterion("answer_more <>", value, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreGreaterThan(String value) {
            addCriterion("answer_more >", value, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreGreaterThanOrEqualTo(String value) {
            addCriterion("answer_more >=", value, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreLessThan(String value) {
            addCriterion("answer_more <", value, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreLessThanOrEqualTo(String value) {
            addCriterion("answer_more <=", value, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreLike(String value) {
            addCriterion("answer_more like", value, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreNotLike(String value) {
            addCriterion("answer_more not like", value, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreIn(List<String> values) {
            addCriterion("answer_more in", values, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreNotIn(List<String> values) {
            addCriterion("answer_more not in", values, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreBetween(String value1, String value2) {
            addCriterion("answer_more between", value1, value2, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerMoreNotBetween(String value1, String value2) {
            addCriterion("answer_more not between", value1, value2, "answerMore");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeIsNull() {
            addCriterion("answer_judge is null");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeIsNotNull() {
            addCriterion("answer_judge is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeEqualTo(String value) {
            addCriterion("answer_judge =", value, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeNotEqualTo(String value) {
            addCriterion("answer_judge <>", value, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeGreaterThan(String value) {
            addCriterion("answer_judge >", value, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeGreaterThanOrEqualTo(String value) {
            addCriterion("answer_judge >=", value, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeLessThan(String value) {
            addCriterion("answer_judge <", value, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeLessThanOrEqualTo(String value) {
            addCriterion("answer_judge <=", value, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeLike(String value) {
            addCriterion("answer_judge like", value, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeNotLike(String value) {
            addCriterion("answer_judge not like", value, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeIn(List<String> values) {
            addCriterion("answer_judge in", values, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeNotIn(List<String> values) {
            addCriterion("answer_judge not in", values, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeBetween(String value1, String value2) {
            addCriterion("answer_judge between", value1, value2, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andAnswerJudgeNotBetween(String value1, String value2) {
            addCriterion("answer_judge not between", value1, value2, "answerJudge");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("total is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("total is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(Integer value) {
            addCriterion("total =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(Integer value) {
            addCriterion("total <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(Integer value) {
            addCriterion("total >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("total >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(Integer value) {
            addCriterion("total <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(Integer value) {
            addCriterion("total <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<Integer> values) {
            addCriterion("total in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<Integer> values) {
            addCriterion("total not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(Integer value1, Integer value2) {
            addCriterion("total between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("total not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreIsNull() {
            addCriterion("select_one_score is null");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreIsNotNull() {
            addCriterion("select_one_score is not null");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreEqualTo(Integer value) {
            addCriterion("select_one_score =", value, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreNotEqualTo(Integer value) {
            addCriterion("select_one_score <>", value, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreGreaterThan(Integer value) {
            addCriterion("select_one_score >", value, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("select_one_score >=", value, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreLessThan(Integer value) {
            addCriterion("select_one_score <", value, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreLessThanOrEqualTo(Integer value) {
            addCriterion("select_one_score <=", value, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreIn(List<Integer> values) {
            addCriterion("select_one_score in", values, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreNotIn(List<Integer> values) {
            addCriterion("select_one_score not in", values, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreBetween(Integer value1, Integer value2) {
            addCriterion("select_one_score between", value1, value2, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectOneScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("select_one_score not between", value1, value2, "selectOneScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreIsNull() {
            addCriterion("select_more_score is null");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreIsNotNull() {
            addCriterion("select_more_score is not null");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreEqualTo(Integer value) {
            addCriterion("select_more_score =", value, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreNotEqualTo(Integer value) {
            addCriterion("select_more_score <>", value, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreGreaterThan(Integer value) {
            addCriterion("select_more_score >", value, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("select_more_score >=", value, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreLessThan(Integer value) {
            addCriterion("select_more_score <", value, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreLessThanOrEqualTo(Integer value) {
            addCriterion("select_more_score <=", value, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreIn(List<Integer> values) {
            addCriterion("select_more_score in", values, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreNotIn(List<Integer> values) {
            addCriterion("select_more_score not in", values, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreBetween(Integer value1, Integer value2) {
            addCriterion("select_more_score between", value1, value2, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectMoreScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("select_more_score not between", value1, value2, "selectMoreScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreIsNull() {
            addCriterion("select_judge_score is null");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreIsNotNull() {
            addCriterion("select_judge_score is not null");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreEqualTo(Integer value) {
            addCriterion("select_judge_score =", value, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreNotEqualTo(Integer value) {
            addCriterion("select_judge_score <>", value, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreGreaterThan(Integer value) {
            addCriterion("select_judge_score >", value, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("select_judge_score >=", value, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreLessThan(Integer value) {
            addCriterion("select_judge_score <", value, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreLessThanOrEqualTo(Integer value) {
            addCriterion("select_judge_score <=", value, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreIn(List<Integer> values) {
            addCriterion("select_judge_score in", values, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreNotIn(List<Integer> values) {
            addCriterion("select_judge_score not in", values, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreBetween(Integer value1, Integer value2) {
            addCriterion("select_judge_score between", value1, value2, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andSelectJudgeScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("select_judge_score not between", value1, value2, "selectJudgeScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreIsNull() {
            addCriterion("pass_score is null");
            return (Criteria) this;
        }

        public Criteria andPassScoreIsNotNull() {
            addCriterion("pass_score is not null");
            return (Criteria) this;
        }

        public Criteria andPassScoreEqualTo(Integer value) {
            addCriterion("pass_score =", value, "passScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreNotEqualTo(Integer value) {
            addCriterion("pass_score <>", value, "passScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreGreaterThan(Integer value) {
            addCriterion("pass_score >", value, "passScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("pass_score >=", value, "passScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreLessThan(Integer value) {
            addCriterion("pass_score <", value, "passScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreLessThanOrEqualTo(Integer value) {
            addCriterion("pass_score <=", value, "passScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreIn(List<Integer> values) {
            addCriterion("pass_score in", values, "passScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreNotIn(List<Integer> values) {
            addCriterion("pass_score not in", values, "passScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreBetween(Integer value1, Integer value2) {
            addCriterion("pass_score between", value1, value2, "passScore");
            return (Criteria) this;
        }

        public Criteria andPassScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("pass_score not between", value1, value2, "passScore");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNull() {
            addCriterion("creat_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIsNotNull() {
            addCriterion("creat_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatTimeEqualTo(Date value) {
            addCriterionForJDBCDate("creat_time =", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotEqualTo(Date value) {
            addCriterionForJDBCDate("creat_time <>", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThan(Date value) {
            addCriterionForJDBCDate("creat_time >", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("creat_time >=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThan(Date value) {
            addCriterionForJDBCDate("creat_time <", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("creat_time <=", value, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeIn(List<Date> values) {
            addCriterionForJDBCDate("creat_time in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotIn(List<Date> values) {
            addCriterionForJDBCDate("creat_time not in", values, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("creat_time between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andCreatTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("creat_time not between", value1, value2, "creatTime");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNull() {
            addCriterion("reserve_two is null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNotNull() {
            addCriterion("reserve_two is not null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoEqualTo(String value) {
            addCriterion("reserve_two =", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotEqualTo(String value) {
            addCriterion("reserve_two <>", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThan(String value) {
            addCriterion("reserve_two >", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_two >=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThan(String value) {
            addCriterion("reserve_two <", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThanOrEqualTo(String value) {
            addCriterion("reserve_two <=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLike(String value) {
            addCriterion("reserve_two like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotLike(String value) {
            addCriterion("reserve_two not like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIn(List<String> values) {
            addCriterion("reserve_two in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotIn(List<String> values) {
            addCriterion("reserve_two not in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoBetween(String value1, String value2) {
            addCriterion("reserve_two between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotBetween(String value1, String value2) {
            addCriterion("reserve_two not between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andPaperTypeIsNull() {
            addCriterion("paper_type is null");
            return (Criteria) this;
        }

        public Criteria andPaperTypeIsNotNull() {
            addCriterion("paper_type is not null");
            return (Criteria) this;
        }

        public Criteria andPaperTypeEqualTo(String value) {
            addCriterion("paper_type =", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotEqualTo(String value) {
            addCriterion("paper_type <>", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeGreaterThan(String value) {
            addCriterion("paper_type >", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeGreaterThanOrEqualTo(String value) {
            addCriterion("paper_type >=", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeLessThan(String value) {
            addCriterion("paper_type <", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeLessThanOrEqualTo(String value) {
            addCriterion("paper_type <=", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeLike(String value) {
            addCriterion("paper_type like", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotLike(String value) {
            addCriterion("paper_type not like", value, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeIn(List<String> values) {
            addCriterion("paper_type in", values, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotIn(List<String> values) {
            addCriterion("paper_type not in", values, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeBetween(String value1, String value2) {
            addCriterion("paper_type between", value1, value2, "paperType");
            return (Criteria) this;
        }

        public Criteria andPaperTypeNotBetween(String value1, String value2) {
            addCriterion("paper_type not between", value1, value2, "paperType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table js_exampaper
     *
     * @mbggenerated do_not_delete_during_merge Wed Aug 02 20:12:20 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table js_exampaper
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}