package cm.cn.po;

public class JsExampaperStu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.stu_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.exampaper_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer exampaperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.score
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Double score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.rate
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_exampaper_stu.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveSix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.id
     *
     * @return the value of js_exampaper_stu.id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.id
     *
     * @param id the value for js_exampaper_stu.id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.stu_id
     *
     * @return the value of js_exampaper_stu.stu_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.stu_id
     *
     * @param stuId the value for js_exampaper_stu.stu_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.exampaper_id
     *
     * @return the value of js_exampaper_stu.exampaper_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getExampaperId() {
        return exampaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.exampaper_id
     *
     * @param exampaperId the value for js_exampaper_stu.exampaper_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setExampaperId(Integer exampaperId) {
        this.exampaperId = exampaperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.score
     *
     * @return the value of js_exampaper_stu.score
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.score
     *
     * @param score the value for js_exampaper_stu.score
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.rate
     *
     * @return the value of js_exampaper_stu.rate
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.rate
     *
     * @param rate the value for js_exampaper_stu.rate
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setRate(String rate) {
        this.rate = rate == null ? null : rate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.reserve_one
     *
     * @return the value of js_exampaper_stu.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.reserve_one
     *
     * @param reserveOne the value for js_exampaper_stu.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.reserve_two
     *
     * @return the value of js_exampaper_stu.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.reserve_two
     *
     * @param reserveTwo the value for js_exampaper_stu.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.reserve_three
     *
     * @return the value of js_exampaper_stu.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.reserve_three
     *
     * @param reserveThree the value for js_exampaper_stu.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.reserve_four
     *
     * @return the value of js_exampaper_stu.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveFour() {
        return reserveFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.reserve_four
     *
     * @param reserveFour the value for js_exampaper_stu.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveFour(String reserveFour) {
        this.reserveFour = reserveFour == null ? null : reserveFour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.reserve_five
     *
     * @return the value of js_exampaper_stu.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveFive() {
        return reserveFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.reserve_five
     *
     * @param reserveFive the value for js_exampaper_stu.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveFive(String reserveFive) {
        this.reserveFive = reserveFive == null ? null : reserveFive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_exampaper_stu.reserve_six
     *
     * @return the value of js_exampaper_stu.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveSix() {
        return reserveSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_exampaper_stu.reserve_six
     *
     * @param reserveSix the value for js_exampaper_stu.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveSix(String reserveSix) {
        this.reserveSix = reserveSix == null ? null : reserveSix.trim();
    }
}