package cm.cn.po;

public class JsLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_level.id
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_level.level
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_level.uplevel
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    private Integer uplevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_level.nextlevel
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    private Integer nextlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_level.name
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_level.reserve_one
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_level.reserve_two
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_level.reserve_four
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    private String reserveFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_level.reserve_three
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    private String reserveThree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_level.id
     *
     * @return the value of js_level.id
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_level.id
     *
     * @param id the value for js_level.id
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_level.level
     *
     * @return the value of js_level.level
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_level.level
     *
     * @param level the value for js_level.level
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_level.uplevel
     *
     * @return the value of js_level.uplevel
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public Integer getUplevel() {
        return uplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_level.uplevel
     *
     * @param uplevel the value for js_level.uplevel
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public void setUplevel(Integer uplevel) {
        this.uplevel = uplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_level.nextlevel
     *
     * @return the value of js_level.nextlevel
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public Integer getNextlevel() {
        return nextlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_level.nextlevel
     *
     * @param nextlevel the value for js_level.nextlevel
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public void setNextlevel(Integer nextlevel) {
        this.nextlevel = nextlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_level.name
     *
     * @return the value of js_level.name
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_level.name
     *
     * @param name the value for js_level.name
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_level.reserve_one
     *
     * @return the value of js_level.reserve_one
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_level.reserve_one
     *
     * @param reserveOne the value for js_level.reserve_one
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_level.reserve_two
     *
     * @return the value of js_level.reserve_two
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_level.reserve_two
     *
     * @param reserveTwo the value for js_level.reserve_two
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_level.reserve_four
     *
     * @return the value of js_level.reserve_four
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public String getReserveFour() {
        return reserveFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_level.reserve_four
     *
     * @param reserveFour the value for js_level.reserve_four
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public void setReserveFour(String reserveFour) {
        this.reserveFour = reserveFour == null ? null : reserveFour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_level.reserve_three
     *
     * @return the value of js_level.reserve_three
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_level.reserve_three
     *
     * @param reserveThree the value for js_level.reserve_three
     *
     * @mbggenerated Fri Aug 25 16:57:36 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }
}