package cm.cn.po;

public class JsQuesion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.type_id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.title
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.content
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.answer
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.creater
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.leibie_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String leibieType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.exam_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String examType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.option_number
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer optionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.difficult_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer difficultType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.know_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String knowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.reserve_one
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.reserve_two
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String reserveTwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.id
     *
     * @return the value of js_quesion.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.id
     *
     * @param id the value for js_quesion.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.type_id
     *
     * @return the value of js_quesion.type_id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.type_id
     *
     * @param typeId the value for js_quesion.type_id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.title
     *
     * @return the value of js_quesion.title
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.title
     *
     * @param title the value for js_quesion.title
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.content
     *
     * @return the value of js_quesion.content
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.content
     *
     * @param content the value for js_quesion.content
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.answer
     *
     * @return the value of js_quesion.answer
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.answer
     *
     * @param answer the value for js_quesion.answer
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.creater
     *
     * @return the value of js_quesion.creater
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.creater
     *
     * @param creater the value for js_quesion.creater
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.leibie_type
     *
     * @return the value of js_quesion.leibie_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getLeibieType() {
        return leibieType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.leibie_type
     *
     * @param leibieType the value for js_quesion.leibie_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setLeibieType(String leibieType) {
        this.leibieType = leibieType == null ? null : leibieType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.exam_type
     *
     * @return the value of js_quesion.exam_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getExamType() {
        return examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.exam_type
     *
     * @param examType the value for js_quesion.exam_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setExamType(String examType) {
        this.examType = examType == null ? null : examType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.option_number
     *
     * @return the value of js_quesion.option_number
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getOptionNumber() {
        return optionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.option_number
     *
     * @param optionNumber the value for js_quesion.option_number
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setOptionNumber(Integer optionNumber) {
        this.optionNumber = optionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.difficult_type
     *
     * @return the value of js_quesion.difficult_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getDifficultType() {
        return difficultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.difficult_type
     *
     * @param difficultType the value for js_quesion.difficult_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setDifficultType(Integer difficultType) {
        this.difficultType = difficultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.know_type
     *
     * @return the value of js_quesion.know_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getKnowType() {
        return knowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.know_type
     *
     * @param knowType the value for js_quesion.know_type
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setKnowType(String knowType) {
        this.knowType = knowType == null ? null : knowType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.reserve_one
     *
     * @return the value of js_quesion.reserve_one
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.reserve_one
     *
     * @param reserveOne the value for js_quesion.reserve_one
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.reserve_two
     *
     * @return the value of js_quesion.reserve_two
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.reserve_two
     *
     * @param reserveTwo the value for js_quesion.reserve_two
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }
}