package cm.cn.po;

public class JsQuestionStu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_question_stu.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_question_stu.stu_id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_question_stu.last_place
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer lastPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_question_stu.total
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_question_stu.reserve_one
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_question_stu.reserve_two
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String reserveTwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_question_stu.id
     *
     * @return the value of js_question_stu.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_question_stu.id
     *
     * @param id the value for js_question_stu.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_question_stu.stu_id
     *
     * @return the value of js_question_stu.stu_id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_question_stu.stu_id
     *
     * @param stuId the value for js_question_stu.stu_id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_question_stu.last_place
     *
     * @return the value of js_question_stu.last_place
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getLastPlace() {
        return lastPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_question_stu.last_place
     *
     * @param lastPlace the value for js_question_stu.last_place
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setLastPlace(Integer lastPlace) {
        this.lastPlace = lastPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_question_stu.total
     *
     * @return the value of js_question_stu.total
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_question_stu.total
     *
     * @param total the value for js_question_stu.total
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_question_stu.reserve_one
     *
     * @return the value of js_question_stu.reserve_one
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_question_stu.reserve_one
     *
     * @param reserveOne the value for js_question_stu.reserve_one
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_question_stu.reserve_two
     *
     * @return the value of js_question_stu.reserve_two
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_question_stu.reserve_two
     *
     * @param reserveTwo the value for js_question_stu.reserve_two
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }
}