package cm.cn.po;

import java.util.ArrayList;
import java.util.List;

public class JsQuesionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public JsQuesionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("type_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(Integer value) {
            addCriterion("type_id =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(Integer value) {
            addCriterion("type_id <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(Integer value) {
            addCriterion("type_id >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("type_id >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(Integer value) {
            addCriterion("type_id <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("type_id <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<Integer> values) {
            addCriterion("type_id in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<Integer> values) {
            addCriterion("type_id not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("type_id between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("type_id not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andAnswerIsNull() {
            addCriterion("answer is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIsNotNull() {
            addCriterion("answer is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerEqualTo(String value) {
            addCriterion("answer =", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotEqualTo(String value) {
            addCriterion("answer <>", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerGreaterThan(String value) {
            addCriterion("answer >", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("answer >=", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLessThan(String value) {
            addCriterion("answer <", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLessThanOrEqualTo(String value) {
            addCriterion("answer <=", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerLike(String value) {
            addCriterion("answer like", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotLike(String value) {
            addCriterion("answer not like", value, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerIn(List<String> values) {
            addCriterion("answer in", values, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotIn(List<String> values) {
            addCriterion("answer not in", values, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerBetween(String value1, String value2) {
            addCriterion("answer between", value1, value2, "answer");
            return (Criteria) this;
        }

        public Criteria andAnswerNotBetween(String value1, String value2) {
            addCriterion("answer not between", value1, value2, "answer");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNull() {
            addCriterion("creater is null");
            return (Criteria) this;
        }

        public Criteria andCreaterIsNotNull() {
            addCriterion("creater is not null");
            return (Criteria) this;
        }

        public Criteria andCreaterEqualTo(String value) {
            addCriterion("creater =", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotEqualTo(String value) {
            addCriterion("creater <>", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThan(String value) {
            addCriterion("creater >", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterGreaterThanOrEqualTo(String value) {
            addCriterion("creater >=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThan(String value) {
            addCriterion("creater <", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLessThanOrEqualTo(String value) {
            addCriterion("creater <=", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterLike(String value) {
            addCriterion("creater like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotLike(String value) {
            addCriterion("creater not like", value, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterIn(List<String> values) {
            addCriterion("creater in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotIn(List<String> values) {
            addCriterion("creater not in", values, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterBetween(String value1, String value2) {
            addCriterion("creater between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andCreaterNotBetween(String value1, String value2) {
            addCriterion("creater not between", value1, value2, "creater");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeIsNull() {
            addCriterion("leibie_type is null");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeIsNotNull() {
            addCriterion("leibie_type is not null");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeEqualTo(String value) {
            addCriterion("leibie_type =", value, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeNotEqualTo(String value) {
            addCriterion("leibie_type <>", value, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeGreaterThan(String value) {
            addCriterion("leibie_type >", value, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeGreaterThanOrEqualTo(String value) {
            addCriterion("leibie_type >=", value, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeLessThan(String value) {
            addCriterion("leibie_type <", value, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeLessThanOrEqualTo(String value) {
            addCriterion("leibie_type <=", value, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeLike(String value) {
            addCriterion("leibie_type like", value, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeNotLike(String value) {
            addCriterion("leibie_type not like", value, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeIn(List<String> values) {
            addCriterion("leibie_type in", values, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeNotIn(List<String> values) {
            addCriterion("leibie_type not in", values, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeBetween(String value1, String value2) {
            addCriterion("leibie_type between", value1, value2, "leibieType");
            return (Criteria) this;
        }

        public Criteria andLeibieTypeNotBetween(String value1, String value2) {
            addCriterion("leibie_type not between", value1, value2, "leibieType");
            return (Criteria) this;
        }

        public Criteria andExamTypeIsNull() {
            addCriterion("exam_type is null");
            return (Criteria) this;
        }

        public Criteria andExamTypeIsNotNull() {
            addCriterion("exam_type is not null");
            return (Criteria) this;
        }

        public Criteria andExamTypeEqualTo(String value) {
            addCriterion("exam_type =", value, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeNotEqualTo(String value) {
            addCriterion("exam_type <>", value, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeGreaterThan(String value) {
            addCriterion("exam_type >", value, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeGreaterThanOrEqualTo(String value) {
            addCriterion("exam_type >=", value, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeLessThan(String value) {
            addCriterion("exam_type <", value, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeLessThanOrEqualTo(String value) {
            addCriterion("exam_type <=", value, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeLike(String value) {
            addCriterion("exam_type like", value, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeNotLike(String value) {
            addCriterion("exam_type not like", value, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeIn(List<String> values) {
            addCriterion("exam_type in", values, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeNotIn(List<String> values) {
            addCriterion("exam_type not in", values, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeBetween(String value1, String value2) {
            addCriterion("exam_type between", value1, value2, "examType");
            return (Criteria) this;
        }

        public Criteria andExamTypeNotBetween(String value1, String value2) {
            addCriterion("exam_type not between", value1, value2, "examType");
            return (Criteria) this;
        }

        public Criteria andOptionNumberIsNull() {
            addCriterion("option_number is null");
            return (Criteria) this;
        }

        public Criteria andOptionNumberIsNotNull() {
            addCriterion("option_number is not null");
            return (Criteria) this;
        }

        public Criteria andOptionNumberEqualTo(Integer value) {
            addCriterion("option_number =", value, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andOptionNumberNotEqualTo(Integer value) {
            addCriterion("option_number <>", value, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andOptionNumberGreaterThan(Integer value) {
            addCriterion("option_number >", value, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andOptionNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("option_number >=", value, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andOptionNumberLessThan(Integer value) {
            addCriterion("option_number <", value, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andOptionNumberLessThanOrEqualTo(Integer value) {
            addCriterion("option_number <=", value, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andOptionNumberIn(List<Integer> values) {
            addCriterion("option_number in", values, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andOptionNumberNotIn(List<Integer> values) {
            addCriterion("option_number not in", values, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andOptionNumberBetween(Integer value1, Integer value2) {
            addCriterion("option_number between", value1, value2, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andOptionNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("option_number not between", value1, value2, "optionNumber");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeIsNull() {
            addCriterion("difficult_type is null");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeIsNotNull() {
            addCriterion("difficult_type is not null");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeEqualTo(Integer value) {
            addCriterion("difficult_type =", value, "difficultType");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeNotEqualTo(Integer value) {
            addCriterion("difficult_type <>", value, "difficultType");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeGreaterThan(Integer value) {
            addCriterion("difficult_type >", value, "difficultType");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("difficult_type >=", value, "difficultType");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeLessThan(Integer value) {
            addCriterion("difficult_type <", value, "difficultType");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeLessThanOrEqualTo(Integer value) {
            addCriterion("difficult_type <=", value, "difficultType");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeIn(List<Integer> values) {
            addCriterion("difficult_type in", values, "difficultType");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeNotIn(List<Integer> values) {
            addCriterion("difficult_type not in", values, "difficultType");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeBetween(Integer value1, Integer value2) {
            addCriterion("difficult_type between", value1, value2, "difficultType");
            return (Criteria) this;
        }

        public Criteria andDifficultTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("difficult_type not between", value1, value2, "difficultType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeIsNull() {
            addCriterion("know_type is null");
            return (Criteria) this;
        }

        public Criteria andKnowTypeIsNotNull() {
            addCriterion("know_type is not null");
            return (Criteria) this;
        }

        public Criteria andKnowTypeEqualTo(String value) {
            addCriterion("know_type =", value, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeNotEqualTo(String value) {
            addCriterion("know_type <>", value, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeGreaterThan(String value) {
            addCriterion("know_type >", value, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeGreaterThanOrEqualTo(String value) {
            addCriterion("know_type >=", value, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeLessThan(String value) {
            addCriterion("know_type <", value, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeLessThanOrEqualTo(String value) {
            addCriterion("know_type <=", value, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeLike(String value) {
            addCriterion("know_type like", value, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeNotLike(String value) {
            addCriterion("know_type not like", value, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeIn(List<String> values) {
            addCriterion("know_type in", values, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeNotIn(List<String> values) {
            addCriterion("know_type not in", values, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeBetween(String value1, String value2) {
            addCriterion("know_type between", value1, value2, "knowType");
            return (Criteria) this;
        }

        public Criteria andKnowTypeNotBetween(String value1, String value2) {
            addCriterion("know_type not between", value1, value2, "knowType");
            return (Criteria) this;
        }

        public Criteria andAnAIsNull() {
            addCriterion("an_A is null");
            return (Criteria) this;
        }

        public Criteria andAnAIsNotNull() {
            addCriterion("an_A is not null");
            return (Criteria) this;
        }

        public Criteria andAnAEqualTo(String value) {
            addCriterion("an_A =", value, "anA");
            return (Criteria) this;
        }

        public Criteria andAnANotEqualTo(String value) {
            addCriterion("an_A <>", value, "anA");
            return (Criteria) this;
        }

        public Criteria andAnAGreaterThan(String value) {
            addCriterion("an_A >", value, "anA");
            return (Criteria) this;
        }

        public Criteria andAnAGreaterThanOrEqualTo(String value) {
            addCriterion("an_A >=", value, "anA");
            return (Criteria) this;
        }

        public Criteria andAnALessThan(String value) {
            addCriterion("an_A <", value, "anA");
            return (Criteria) this;
        }

        public Criteria andAnALessThanOrEqualTo(String value) {
            addCriterion("an_A <=", value, "anA");
            return (Criteria) this;
        }

        public Criteria andAnALike(String value) {
            addCriterion("an_A like", value, "anA");
            return (Criteria) this;
        }

        public Criteria andAnANotLike(String value) {
            addCriterion("an_A not like", value, "anA");
            return (Criteria) this;
        }

        public Criteria andAnAIn(List<String> values) {
            addCriterion("an_A in", values, "anA");
            return (Criteria) this;
        }

        public Criteria andAnANotIn(List<String> values) {
            addCriterion("an_A not in", values, "anA");
            return (Criteria) this;
        }

        public Criteria andAnABetween(String value1, String value2) {
            addCriterion("an_A between", value1, value2, "anA");
            return (Criteria) this;
        }

        public Criteria andAnANotBetween(String value1, String value2) {
            addCriterion("an_A not between", value1, value2, "anA");
            return (Criteria) this;
        }

        public Criteria andAnBIsNull() {
            addCriterion("an_B is null");
            return (Criteria) this;
        }

        public Criteria andAnBIsNotNull() {
            addCriterion("an_B is not null");
            return (Criteria) this;
        }

        public Criteria andAnBEqualTo(String value) {
            addCriterion("an_B =", value, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBNotEqualTo(String value) {
            addCriterion("an_B <>", value, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBGreaterThan(String value) {
            addCriterion("an_B >", value, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBGreaterThanOrEqualTo(String value) {
            addCriterion("an_B >=", value, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBLessThan(String value) {
            addCriterion("an_B <", value, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBLessThanOrEqualTo(String value) {
            addCriterion("an_B <=", value, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBLike(String value) {
            addCriterion("an_B like", value, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBNotLike(String value) {
            addCriterion("an_B not like", value, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBIn(List<String> values) {
            addCriterion("an_B in", values, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBNotIn(List<String> values) {
            addCriterion("an_B not in", values, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBBetween(String value1, String value2) {
            addCriterion("an_B between", value1, value2, "anB");
            return (Criteria) this;
        }

        public Criteria andAnBNotBetween(String value1, String value2) {
            addCriterion("an_B not between", value1, value2, "anB");
            return (Criteria) this;
        }

        public Criteria andAnCIsNull() {
            addCriterion("an_C is null");
            return (Criteria) this;
        }

        public Criteria andAnCIsNotNull() {
            addCriterion("an_C is not null");
            return (Criteria) this;
        }

        public Criteria andAnCEqualTo(String value) {
            addCriterion("an_C =", value, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCNotEqualTo(String value) {
            addCriterion("an_C <>", value, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCGreaterThan(String value) {
            addCriterion("an_C >", value, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCGreaterThanOrEqualTo(String value) {
            addCriterion("an_C >=", value, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCLessThan(String value) {
            addCriterion("an_C <", value, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCLessThanOrEqualTo(String value) {
            addCriterion("an_C <=", value, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCLike(String value) {
            addCriterion("an_C like", value, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCNotLike(String value) {
            addCriterion("an_C not like", value, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCIn(List<String> values) {
            addCriterion("an_C in", values, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCNotIn(List<String> values) {
            addCriterion("an_C not in", values, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCBetween(String value1, String value2) {
            addCriterion("an_C between", value1, value2, "anC");
            return (Criteria) this;
        }

        public Criteria andAnCNotBetween(String value1, String value2) {
            addCriterion("an_C not between", value1, value2, "anC");
            return (Criteria) this;
        }

        public Criteria andAnDIsNull() {
            addCriterion("an_D is null");
            return (Criteria) this;
        }

        public Criteria andAnDIsNotNull() {
            addCriterion("an_D is not null");
            return (Criteria) this;
        }

        public Criteria andAnDEqualTo(String value) {
            addCriterion("an_D =", value, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDNotEqualTo(String value) {
            addCriterion("an_D <>", value, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDGreaterThan(String value) {
            addCriterion("an_D >", value, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDGreaterThanOrEqualTo(String value) {
            addCriterion("an_D >=", value, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDLessThan(String value) {
            addCriterion("an_D <", value, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDLessThanOrEqualTo(String value) {
            addCriterion("an_D <=", value, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDLike(String value) {
            addCriterion("an_D like", value, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDNotLike(String value) {
            addCriterion("an_D not like", value, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDIn(List<String> values) {
            addCriterion("an_D in", values, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDNotIn(List<String> values) {
            addCriterion("an_D not in", values, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDBetween(String value1, String value2) {
            addCriterion("an_D between", value1, value2, "anD");
            return (Criteria) this;
        }

        public Criteria andAnDNotBetween(String value1, String value2) {
            addCriterion("an_D not between", value1, value2, "anD");
            return (Criteria) this;
        }

        public Criteria andReserveOneIsNull() {
            addCriterion("reserve_one is null");
            return (Criteria) this;
        }

        public Criteria andReserveOneIsNotNull() {
            addCriterion("reserve_one is not null");
            return (Criteria) this;
        }

        public Criteria andReserveOneEqualTo(String value) {
            addCriterion("reserve_one =", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotEqualTo(String value) {
            addCriterion("reserve_one <>", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneGreaterThan(String value) {
            addCriterion("reserve_one >", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_one >=", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLessThan(String value) {
            addCriterion("reserve_one <", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLessThanOrEqualTo(String value) {
            addCriterion("reserve_one <=", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneLike(String value) {
            addCriterion("reserve_one like", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotLike(String value) {
            addCriterion("reserve_one not like", value, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneIn(List<String> values) {
            addCriterion("reserve_one in", values, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotIn(List<String> values) {
            addCriterion("reserve_one not in", values, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneBetween(String value1, String value2) {
            addCriterion("reserve_one between", value1, value2, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveOneNotBetween(String value1, String value2) {
            addCriterion("reserve_one not between", value1, value2, "reserveOne");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNull() {
            addCriterion("reserve_two is null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIsNotNull() {
            addCriterion("reserve_two is not null");
            return (Criteria) this;
        }

        public Criteria andReserveTwoEqualTo(String value) {
            addCriterion("reserve_two =", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotEqualTo(String value) {
            addCriterion("reserve_two <>", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThan(String value) {
            addCriterion("reserve_two >", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_two >=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThan(String value) {
            addCriterion("reserve_two <", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLessThanOrEqualTo(String value) {
            addCriterion("reserve_two <=", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoLike(String value) {
            addCriterion("reserve_two like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotLike(String value) {
            addCriterion("reserve_two not like", value, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoIn(List<String> values) {
            addCriterion("reserve_two in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotIn(List<String> values) {
            addCriterion("reserve_two not in", values, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoBetween(String value1, String value2) {
            addCriterion("reserve_two between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveTwoNotBetween(String value1, String value2) {
            addCriterion("reserve_two not between", value1, value2, "reserveTwo");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIsNull() {
            addCriterion("reserve_three is null");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIsNotNull() {
            addCriterion("reserve_three is not null");
            return (Criteria) this;
        }

        public Criteria andReserveThreeEqualTo(String value) {
            addCriterion("reserve_three =", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotEqualTo(String value) {
            addCriterion("reserve_three <>", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeGreaterThan(String value) {
            addCriterion("reserve_three >", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_three >=", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLessThan(String value) {
            addCriterion("reserve_three <", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLessThanOrEqualTo(String value) {
            addCriterion("reserve_three <=", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeLike(String value) {
            addCriterion("reserve_three like", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotLike(String value) {
            addCriterion("reserve_three not like", value, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeIn(List<String> values) {
            addCriterion("reserve_three in", values, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotIn(List<String> values) {
            addCriterion("reserve_three not in", values, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeBetween(String value1, String value2) {
            addCriterion("reserve_three between", value1, value2, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveThreeNotBetween(String value1, String value2) {
            addCriterion("reserve_three not between", value1, value2, "reserveThree");
            return (Criteria) this;
        }

        public Criteria andReserveFourIsNull() {
            addCriterion("reserve_four is null");
            return (Criteria) this;
        }

        public Criteria andReserveFourIsNotNull() {
            addCriterion("reserve_four is not null");
            return (Criteria) this;
        }

        public Criteria andReserveFourEqualTo(String value) {
            addCriterion("reserve_four =", value, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourNotEqualTo(String value) {
            addCriterion("reserve_four <>", value, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourGreaterThan(String value) {
            addCriterion("reserve_four >", value, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_four >=", value, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourLessThan(String value) {
            addCriterion("reserve_four <", value, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourLessThanOrEqualTo(String value) {
            addCriterion("reserve_four <=", value, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourLike(String value) {
            addCriterion("reserve_four like", value, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourNotLike(String value) {
            addCriterion("reserve_four not like", value, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourIn(List<String> values) {
            addCriterion("reserve_four in", values, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourNotIn(List<String> values) {
            addCriterion("reserve_four not in", values, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourBetween(String value1, String value2) {
            addCriterion("reserve_four between", value1, value2, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFourNotBetween(String value1, String value2) {
            addCriterion("reserve_four not between", value1, value2, "reserveFour");
            return (Criteria) this;
        }

        public Criteria andReserveFiveIsNull() {
            addCriterion("reserve_five is null");
            return (Criteria) this;
        }

        public Criteria andReserveFiveIsNotNull() {
            addCriterion("reserve_five is not null");
            return (Criteria) this;
        }

        public Criteria andReserveFiveEqualTo(String value) {
            addCriterion("reserve_five =", value, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveNotEqualTo(String value) {
            addCriterion("reserve_five <>", value, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveGreaterThan(String value) {
            addCriterion("reserve_five >", value, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_five >=", value, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveLessThan(String value) {
            addCriterion("reserve_five <", value, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveLessThanOrEqualTo(String value) {
            addCriterion("reserve_five <=", value, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveLike(String value) {
            addCriterion("reserve_five like", value, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveNotLike(String value) {
            addCriterion("reserve_five not like", value, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveIn(List<String> values) {
            addCriterion("reserve_five in", values, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveNotIn(List<String> values) {
            addCriterion("reserve_five not in", values, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveBetween(String value1, String value2) {
            addCriterion("reserve_five between", value1, value2, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveFiveNotBetween(String value1, String value2) {
            addCriterion("reserve_five not between", value1, value2, "reserveFive");
            return (Criteria) this;
        }

        public Criteria andReserveSixIsNull() {
            addCriterion("reserve_six is null");
            return (Criteria) this;
        }

        public Criteria andReserveSixIsNotNull() {
            addCriterion("reserve_six is not null");
            return (Criteria) this;
        }

        public Criteria andReserveSixEqualTo(String value) {
            addCriterion("reserve_six =", value, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixNotEqualTo(String value) {
            addCriterion("reserve_six <>", value, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixGreaterThan(String value) {
            addCriterion("reserve_six >", value, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixGreaterThanOrEqualTo(String value) {
            addCriterion("reserve_six >=", value, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixLessThan(String value) {
            addCriterion("reserve_six <", value, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixLessThanOrEqualTo(String value) {
            addCriterion("reserve_six <=", value, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixLike(String value) {
            addCriterion("reserve_six like", value, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixNotLike(String value) {
            addCriterion("reserve_six not like", value, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixIn(List<String> values) {
            addCriterion("reserve_six in", values, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixNotIn(List<String> values) {
            addCriterion("reserve_six not in", values, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixBetween(String value1, String value2) {
            addCriterion("reserve_six between", value1, value2, "reserveSix");
            return (Criteria) this;
        }

        public Criteria andReserveSixNotBetween(String value1, String value2) {
            addCriterion("reserve_six not between", value1, value2, "reserveSix");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table js_quesion
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 07 15:23:31 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table js_quesion
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}