package cm.cn.po;

public class JsQuesion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.type_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.title
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.answer
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String answer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.creater
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String creater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.leibie_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String leibieType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.exam_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String examType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.option_number
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer optionNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.difficult_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private Integer difficultType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.know_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String knowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.an_A
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String anA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.an_B
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String anB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.an_C
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String anC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.an_D
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String anD;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_quesion.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    private String reserveSix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.id
     *
     * @return the value of js_quesion.id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.id
     *
     * @param id the value for js_quesion.id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.type_id
     *
     * @return the value of js_quesion.type_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.type_id
     *
     * @param typeId the value for js_quesion.type_id
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.title
     *
     * @return the value of js_quesion.title
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.title
     *
     * @param title the value for js_quesion.title
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.answer
     *
     * @return the value of js_quesion.answer
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.answer
     *
     * @param answer the value for js_quesion.answer
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.creater
     *
     * @return the value of js_quesion.creater
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getCreater() {
        return creater;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.creater
     *
     * @param creater the value for js_quesion.creater
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setCreater(String creater) {
        this.creater = creater == null ? null : creater.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.leibie_type
     *
     * @return the value of js_quesion.leibie_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getLeibieType() {
        return leibieType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.leibie_type
     *
     * @param leibieType the value for js_quesion.leibie_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setLeibieType(String leibieType) {
        this.leibieType = leibieType == null ? null : leibieType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.exam_type
     *
     * @return the value of js_quesion.exam_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getExamType() {
        return examType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.exam_type
     *
     * @param examType the value for js_quesion.exam_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setExamType(String examType) {
        this.examType = examType == null ? null : examType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.option_number
     *
     * @return the value of js_quesion.option_number
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getOptionNumber() {
        return optionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.option_number
     *
     * @param optionNumber the value for js_quesion.option_number
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setOptionNumber(Integer optionNumber) {
        this.optionNumber = optionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.difficult_type
     *
     * @return the value of js_quesion.difficult_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public Integer getDifficultType() {
        return difficultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.difficult_type
     *
     * @param difficultType the value for js_quesion.difficult_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setDifficultType(Integer difficultType) {
        this.difficultType = difficultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.know_type
     *
     * @return the value of js_quesion.know_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getKnowType() {
        return knowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.know_type
     *
     * @param knowType the value for js_quesion.know_type
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setKnowType(String knowType) {
        this.knowType = knowType == null ? null : knowType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.an_A
     *
     * @return the value of js_quesion.an_A
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnA() {
        return anA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.an_A
     *
     * @param anA the value for js_quesion.an_A
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnA(String anA) {
        this.anA = anA == null ? null : anA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.an_B
     *
     * @return the value of js_quesion.an_B
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnB() {
        return anB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.an_B
     *
     * @param anB the value for js_quesion.an_B
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnB(String anB) {
        this.anB = anB == null ? null : anB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.an_C
     *
     * @return the value of js_quesion.an_C
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnC() {
        return anC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.an_C
     *
     * @param anC the value for js_quesion.an_C
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnC(String anC) {
        this.anC = anC == null ? null : anC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.an_D
     *
     * @return the value of js_quesion.an_D
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getAnD() {
        return anD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.an_D
     *
     * @param anD the value for js_quesion.an_D
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setAnD(String anD) {
        this.anD = anD == null ? null : anD.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.reserve_one
     *
     * @return the value of js_quesion.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.reserve_one
     *
     * @param reserveOne the value for js_quesion.reserve_one
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.reserve_two
     *
     * @return the value of js_quesion.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.reserve_two
     *
     * @param reserveTwo the value for js_quesion.reserve_two
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.reserve_three
     *
     * @return the value of js_quesion.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.reserve_three
     *
     * @param reserveThree the value for js_quesion.reserve_three
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.reserve_four
     *
     * @return the value of js_quesion.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveFour() {
        return reserveFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.reserve_four
     *
     * @param reserveFour the value for js_quesion.reserve_four
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveFour(String reserveFour) {
        this.reserveFour = reserveFour == null ? null : reserveFour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.reserve_five
     *
     * @return the value of js_quesion.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveFive() {
        return reserveFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.reserve_five
     *
     * @param reserveFive the value for js_quesion.reserve_five
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveFive(String reserveFive) {
        this.reserveFive = reserveFive == null ? null : reserveFive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_quesion.reserve_six
     *
     * @return the value of js_quesion.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public String getReserveSix() {
        return reserveSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_quesion.reserve_six
     *
     * @param reserveSix the value for js_quesion.reserve_six
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    public void setReserveSix(String reserveSix) {
        this.reserveSix = reserveSix == null ? null : reserveSix.trim();
    }
}