package cm.cn.po;

public class JsRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_role.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_role.name
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_role.code
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_role.id
     *
     * @return the value of js_role.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_role.id
     *
     * @param id the value for js_role.id
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_role.name
     *
     * @return the value of js_role.name
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_role.name
     *
     * @param name the value for js_role.name
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_role.code
     *
     * @return the value of js_role.code
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_role.code
     *
     * @param code the value for js_role.code
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}