package cm.cn.po;

public class JsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.id
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.username
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.password
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.realname
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.pic
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.phone
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.idcard
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.stu_type
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String stuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.reserve_two
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.reserve_three
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.reserve_four
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String reserveFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.reserve_five
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String reserveFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.reserve_six
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String reserveSix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.role_id
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.check_code
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private String checkCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_user.chenk_time
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    private Long chenkTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.id
     *
     * @return the value of js_user.id
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.id
     *
     * @param id the value for js_user.id
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.username
     *
     * @return the value of js_user.username
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.username
     *
     * @param username the value for js_user.username
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.password
     *
     * @return the value of js_user.password
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.password
     *
     * @param password the value for js_user.password
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.realname
     *
     * @return the value of js_user.realname
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.realname
     *
     * @param realname the value for js_user.realname
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.pic
     *
     * @return the value of js_user.pic
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.pic
     *
     * @param pic the value for js_user.pic
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.phone
     *
     * @return the value of js_user.phone
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.phone
     *
     * @param phone the value for js_user.phone
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.idcard
     *
     * @return the value of js_user.idcard
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.idcard
     *
     * @param idcard the value for js_user.idcard
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.stu_type
     *
     * @return the value of js_user.stu_type
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getStuType() {
        return stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.stu_type
     *
     * @param stuType the value for js_user.stu_type
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setStuType(String stuType) {
        this.stuType = stuType == null ? null : stuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.reserve_two
     *
     * @return the value of js_user.reserve_two
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.reserve_two
     *
     * @param reserveTwo the value for js_user.reserve_two
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.reserve_three
     *
     * @return the value of js_user.reserve_three
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.reserve_three
     *
     * @param reserveThree the value for js_user.reserve_three
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.reserve_four
     *
     * @return the value of js_user.reserve_four
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getReserveFour() {
        return reserveFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.reserve_four
     *
     * @param reserveFour the value for js_user.reserve_four
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setReserveFour(String reserveFour) {
        this.reserveFour = reserveFour == null ? null : reserveFour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.reserve_five
     *
     * @return the value of js_user.reserve_five
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getReserveFive() {
        return reserveFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.reserve_five
     *
     * @param reserveFive the value for js_user.reserve_five
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setReserveFive(String reserveFive) {
        this.reserveFive = reserveFive == null ? null : reserveFive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.reserve_six
     *
     * @return the value of js_user.reserve_six
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getReserveSix() {
        return reserveSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.reserve_six
     *
     * @param reserveSix the value for js_user.reserve_six
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setReserveSix(String reserveSix) {
        this.reserveSix = reserveSix == null ? null : reserveSix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.role_id
     *
     * @return the value of js_user.role_id
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.role_id
     *
     * @param roleId the value for js_user.role_id
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.check_code
     *
     * @return the value of js_user.check_code
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public String getCheckCode() {
        return checkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.check_code
     *
     * @param checkCode the value for js_user.check_code
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setCheckCode(String checkCode) {
        this.checkCode = checkCode == null ? null : checkCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_user.chenk_time
     *
     * @return the value of js_user.chenk_time
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public Long getChenkTime() {
        return chenkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_user.chenk_time
     *
     * @param chenkTime the value for js_user.chenk_time
     *
     * @mbggenerated Wed Aug 09 18:22:33 CST 2017
     */
    public void setChenkTime(Long chenkTime) {
        this.chenkTime = chenkTime;
    }
}