package cm.cn.po;

public class JsVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.id
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.name
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.url
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.content
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.uploader
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    private String uploader;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.id
     *
     * @return the value of js_video.id
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.id
     *
     * @param id the value for js_video.id
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.name
     *
     * @return the value of js_video.name
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.name
     *
     * @param name the value for js_video.name
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.url
     *
     * @return the value of js_video.url
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.url
     *
     * @param url the value for js_video.url
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.content
     *
     * @return the value of js_video.content
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.content
     *
     * @param content the value for js_video.content
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.uploader
     *
     * @return the value of js_video.uploader
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public String getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.uploader
     *
     * @param uploader the value for js_video.uploader
     *
     * @mbggenerated Fri Aug 18 14:20:16 CST 2017
     */
    public void setUploader(String uploader) {
        this.uploader = uploader == null ? null : uploader.trim();
    }
}