package cm.cn.po;

import java.util.Date;

public class JsVideo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.id
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.name
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.url
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.content
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.uploader
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String uploader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.pic
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String pic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.reserve_one
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String reserveOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.reserve_two
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String reserveTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.reserve_three
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String reserveThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.reserve_four
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String reserveFour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.reserve_five
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String reserveFive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.reserve_six
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String reserveSix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.picname
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private String picname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column js_video.date
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    private Date date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.id
     *
     * @return the value of js_video.id
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.id
     *
     * @param id the value for js_video.id
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.name
     *
     * @return the value of js_video.name
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.name
     *
     * @param name the value for js_video.name
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.url
     *
     * @return the value of js_video.url
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.url
     *
     * @param url the value for js_video.url
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.content
     *
     * @return the value of js_video.content
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.content
     *
     * @param content the value for js_video.content
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.uploader
     *
     * @return the value of js_video.uploader
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.uploader
     *
     * @param uploader the value for js_video.uploader
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setUploader(String uploader) {
        this.uploader = uploader == null ? null : uploader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.pic
     *
     * @return the value of js_video.pic
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.pic
     *
     * @param pic the value for js_video.pic
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.reserve_one
     *
     * @return the value of js_video.reserve_one
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getReserveOne() {
        return reserveOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.reserve_one
     *
     * @param reserveOne the value for js_video.reserve_one
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setReserveOne(String reserveOne) {
        this.reserveOne = reserveOne == null ? null : reserveOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.reserve_two
     *
     * @return the value of js_video.reserve_two
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getReserveTwo() {
        return reserveTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.reserve_two
     *
     * @param reserveTwo the value for js_video.reserve_two
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setReserveTwo(String reserveTwo) {
        this.reserveTwo = reserveTwo == null ? null : reserveTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.reserve_three
     *
     * @return the value of js_video.reserve_three
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getReserveThree() {
        return reserveThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.reserve_three
     *
     * @param reserveThree the value for js_video.reserve_three
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setReserveThree(String reserveThree) {
        this.reserveThree = reserveThree == null ? null : reserveThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.reserve_four
     *
     * @return the value of js_video.reserve_four
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getReserveFour() {
        return reserveFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.reserve_four
     *
     * @param reserveFour the value for js_video.reserve_four
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setReserveFour(String reserveFour) {
        this.reserveFour = reserveFour == null ? null : reserveFour.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.reserve_five
     *
     * @return the value of js_video.reserve_five
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getReserveFive() {
        return reserveFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.reserve_five
     *
     * @param reserveFive the value for js_video.reserve_five
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setReserveFive(String reserveFive) {
        this.reserveFive = reserveFive == null ? null : reserveFive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.reserve_six
     *
     * @return the value of js_video.reserve_six
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getReserveSix() {
        return reserveSix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.reserve_six
     *
     * @param reserveSix the value for js_video.reserve_six
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setReserveSix(String reserveSix) {
        this.reserveSix = reserveSix == null ? null : reserveSix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.picname
     *
     * @return the value of js_video.picname
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public String getPicname() {
        return picname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.picname
     *
     * @param picname the value for js_video.picname
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setPicname(String picname) {
        this.picname = picname == null ? null : picname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column js_video.date
     *
     * @return the value of js_video.date
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column js_video.date
     *
     * @param date the value for js_video.date
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    public void setDate(Date date) {
        this.date = date;
    }
}