package cm.cn.mapper;

import cm.cn.po.JsCasequestion;
import cm.cn.po.JsCasequestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsCasequestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int countByExample(JsCasequestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int deleteByExample(JsCasequestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int insert(JsCasequestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int insertSelective(JsCasequestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    List<JsCasequestion> selectByExample(JsCasequestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    JsCasequestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsCasequestion record, @Param("example") JsCasequestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByExample(@Param("record") JsCasequestion record, @Param("example") JsCasequestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(JsCasequestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_casequestion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByPrimaryKey(JsCasequestion record);
}