package cm.cn.mapper;

import cm.cn.po.JsExampaperStu;
import cm.cn.po.JsExampaperStuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsExampaperStuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int countByExample(JsExampaperStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int deleteByExample(JsExampaperStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int insert(JsExampaperStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int insertSelective(JsExampaperStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    List<JsExampaperStu> selectByExample(JsExampaperStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    JsExampaperStu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsExampaperStu record, @Param("example") JsExampaperStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int updateByExample(@Param("record") JsExampaperStu record, @Param("example") JsExampaperStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int updateByPrimaryKeySelective(JsExampaperStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_exampaper_stu
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int updateByPrimaryKey(JsExampaperStu record);
}