package cm.cn.mapper;

import cm.cn.po.JsQuesion;
import cm.cn.po.JsQuesionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsQuesionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int countByExample(JsQuesionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int deleteByExample(JsQuesionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int insert(JsQuesion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int insertSelective(JsQuesion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    List<JsQuesion> selectByExample(JsQuesionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    JsQuesion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsQuesion record, @Param("example") JsQuesionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByExample(@Param("record") JsQuesion record, @Param("example") JsQuesionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(JsQuesion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_quesion
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByPrimaryKey(JsQuesion record);
}