package cm.cn.mapper;

import cm.cn.po.JsQuestionStu;
import cm.cn.po.JsQuestionStuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsQuestionStuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int countByExample(JsQuestionStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int deleteByExample(JsQuestionStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int insert(JsQuestionStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int insertSelective(JsQuestionStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    List<JsQuestionStu> selectByExample(JsQuestionStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    JsQuestionStu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsQuestionStu record, @Param("example") JsQuestionStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByExample(@Param("record") JsQuestionStu record, @Param("example") JsQuestionStuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByPrimaryKeySelective(JsQuestionStu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_question_stu
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByPrimaryKey(JsQuestionStu record);
}