package cm.cn.mapper;

import cm.cn.po.JsRole;
import cm.cn.po.JsRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int countByExample(JsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int deleteByExample(JsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int insert(JsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int insertSelective(JsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    List<JsRole> selectByExample(JsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    JsRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsRole record, @Param("example") JsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int updateByExample(@Param("record") JsRole record, @Param("example") JsRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int updateByPrimaryKeySelective(JsRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_role
     *
     * @mbggenerated Mon Aug 07 15:23:31 CST 2017
     */
    int updateByPrimaryKey(JsRole record);
}