package cm.cn.mapper;

import cm.cn.po.JsUserRole;
import cm.cn.po.JsUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int countByExample(JsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int deleteByExample(JsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int insert(JsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int insertSelective(JsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    List<JsUserRole> selectByExample(JsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    JsUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsUserRole record, @Param("example") JsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:21 CST 2017
     */
    int updateByExample(@Param("record") JsUserRole record, @Param("example") JsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:21 CST 2017
     */
    int updateByPrimaryKeySelective(JsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_user_role
     *
     * @mbggenerated Wed Aug 02 20:12:21 CST 2017
     */
    int updateByPrimaryKey(JsUserRole record);
}