package cm.cn.mapper;

import cm.cn.po.JsVideo;
import cm.cn.po.JsVideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    int countByExample(JsVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    int deleteByExample(JsVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    int insert(JsVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    int insertSelective(JsVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    List<JsVideo> selectByExample(JsVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    JsVideo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") JsVideo record, @Param("example") JsVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    int updateByExample(@Param("record") JsVideo record, @Param("example") JsVideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    int updateByPrimaryKeySelective(JsVideo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table js_video
     *
     * @mbggenerated Sat Aug 19 13:53:57 CST 2017
     */
    int updateByPrimaryKey(JsVideo record);
}